keys:
  - &txg0fk3 age1zz4zw0lxpm95wyg8p42npcjsr4tqf2zem6x0d9xj9dd9wff0ndwslmmmsj

  - &orion age1jlcyfl9wrctacjqyfuctfl9v44q7smagdzexjkal824azka43g2ssc8vuu
  - &hydra age1arrhdr4vtn03c567rmdsuu96ppr9nmcy364uq08ygqelvqd2afcslg2jnc

creation_rules:
  - path_regex: secrets/orion\.(yaml|json)$
    key_groups: 
    - age: [ *txg0fk3, *orion ]

  - path_regex: secrets/hydra\.(yaml|json)$ 
    key_groups: 
      - age: [ *txg0fk3, *hydra]

  - path_regex: secrets/common\.(yaml|json)$
    key_groups:
      - age: [*txg0fk3, *orion, *hydra]
